import logging
from typing import Optional, AsyncIterator
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from src.llm.chain import KYCChain
from src.llm.response import KYCResponse
from src.api.dependencies import get_chain

log    = logging.getLogger(__name__)
router = APIRouter(tags=["query"])


# Request / Response models

class QueryRequest(BaseModel):
    query:           str          = Field(..., min_length=5, max_length=500)
    chapter:         Optional[str] = None
    include_deleted: bool          = False

class QueryResponse(BaseModel):
    query:                  str
    answer:                 str
    citations:              list[dict]
    has_deleted_provisions: bool
    has_amended_provisions: bool
    chunks_used:            int
    elapsed_sec:            float
    timestamp:              str


# /query — synchronous 

@router.post("/query", response_model=QueryResponse)
async def query_endpoint(
    req:   QueryRequest,
    chain: KYCChain = Depends(get_chain),
):
    """
    Standard RAG query. Returns full answer + citations.
    Routing (FPI / historical / chapter / general) is handled automatically.
    """
    try:
        response: KYCResponse = await chain.ainvoke(
            req.query,
            chapter         = req.chapter,
            include_deleted = req.include_deleted,
        ) if req.chapter else await chain.ainvoke(req.query, include_deleted=req.include_deleted)

        # Fire-and-forget MLflow logging (non-blocking)
        intent, chapter_hint = chain.router.classify(req.query)
        log.info(
            "query_metrics",
            extra={
                "intent":           intent.value,
                "citation_coverage": len(response.citations) / max(response.chunks_used, 1),
                "has_deleted":      response.has_deleted_provisions,
                "has_amended":      response.has_amended_provisions,
                "elapsed_sec":      response.elapsed_sec,
                "chapter"    :     {chapter_hint},
            }
        )

        return QueryResponse(
            query                  = response.query,
            answer                 = response.answer,
            citations              = [c.model_dump() for c in response.citations],
            has_deleted_provisions = response.has_deleted_provisions,
            has_amended_provisions = response.has_amended_provisions,
            chunks_used            = response.chunks_used,
            elapsed_sec            = response.elapsed_sec,
            timestamp              = response.timestamp,
        )
    except Exception as e:
        log.exception(f"Query failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# /query/route — unified entry (calls router internally) 

@router.post("/query/route", response_model=QueryResponse)
async def query_routed(
    req:   QueryRequest,
    chain: KYCChain = Depends(get_chain),
):
    """
    Fully routed endpoint — intent classified automatically.
    Dispatches to ask_fpi / ask_chapter / ask_with_history / invoke.
    """
    try:
        intent, chapter_hint = chain.router.classify(req.query)

        response = chain.query(req.query)

        log.info(
            "query_metrics",
            extra={
                "intent":           intent.value,
                "citation_coverage": len(response.citations) / max(response.chunks_used, 1),
                "has_deleted":      response.has_deleted_provisions,
                "has_amended":      response.has_amended_provisions,
                "elapsed_sec":      response.elapsed_sec,
                "chapter"    :     {chapter_hint},
            }
        )

        return QueryResponse(
            query                  = response.query,
            answer                 = response.answer,
            citations              = [c.model_dump() for c in response.citations],
            has_deleted_provisions = response.has_deleted_provisions,
            has_amended_provisions = response.has_amended_provisions,
            chunks_used            = response.chunks_used,
            elapsed_sec            = response.elapsed_sec,
            timestamp              = response.timestamp,
        )
    except Exception as e:
        log.exception(f"Routed query failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# /query/stream — streaming SSE

@router.post("/query/stream")
async def query_stream(
    req:   QueryRequest,
    chain: KYCChain = Depends(get_chain),
):
    """
    Server-Sent Events streaming endpoint.
    Tokens arrive as they're generated by Groq.

    Client usage (JS):
        const evtSource = new EventSource('/query/stream');
        evtSource.onmessage = e => process(e.data);
    """
    async def token_generator() -> AsyncIterator[str]:
        try:
            for token in chain.stream(
                req.query,
                include_deleted=req.include_deleted,
            ):
                yield f"data: {token}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as e:
            yield f"data: [ERROR] {str(e)}\n\n"

    return StreamingResponse(
        token_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control":               "no-cache",
            "X-Accel-Buffering":           "no",   # disables nginx buffering
            "Access-Control-Allow-Origin": "*",
        },
    )
