name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.in') }}

      - name: Install dependencies
        run: pip install -r requirements/dev.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: pytest tests/test_ingestion.py -v -k "not Integration and not Processed"


  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        run: |
          IMAGE=$ECR_REGISTRY/rag-kyc:${{ github.sha }}
          docker build -t $IMAGE .
          docker tag  $IMAGE $ECR_REGISTRY/rag-kyc:latest
          docker push $IMAGE
          docker push $ECR_REGISTRY/rag-kyc:latest

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-south-1

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          port:     22
          script: |
            ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}

            # Login to ECR from EC2
            aws ecr get-login-password --region ap-south-1 | \
              docker login --username AWS --password-stdin $ECR_REGISTRY

            # Pull latest image
            docker pull $ECR_REGISTRY/rag-kyc:latest

            # Stop & remove old container if exists
            docker stop rag-kyc || true
            docker rm   rag-kyc || true

            # Run new container
            docker run -d --name rag-kyc -p 8000:8000 \
              -e GROQ_API_KEY='${{ secrets.GROQ_API_KEY }}' \
              -e QDRANT_URL='${{ secrets.QDRANT_URL }}' \
              -e QDRANT_API_KEY='${{ secrets.QDRANT_API_KEY }}' \
              $ECR_REGISTRY/rag-kyc:latest


  # Deploy to HF Spaces 
  deploy-hf:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare HF deploy folder
        run: |
          mkdir hf_deploy

          cp Dockerfile hf_deploy/
          cp params.yaml hf_deploy/
          cp README.md hf_deploy/

          mkdir -p hf_deploy/src
          mkdir -p hf_deploy/requirements
          mkdir -p hf_deploy/scripts

          cp -r src/* hf_deploy/src/
          cp requirements/prod.txt hf_deploy/requirements/
          cp scripts/warmup_models.py hf_deploy/scripts/

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf_deploy

          git init
          git branch -M main
          git config user.email "ci@github.com"
          git config user.name "GitHub CI"

          git remote add space \
            https://user:$HF_TOKEN@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/rag-kyc

          git add .
          git commit -m "deploy to HF Space"
          git push space main --force
